version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./cache:/var/cache/nginx
    depends_on:
      - backend
    container_name: nginx

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "5000"